name: build-and-deploy

on:
  # 每当 push 到 master 分支时触发部署
  push:
    # branches: [master]
    branches: [1]

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest

    # env:
    #   NODE_VERSION: 20

    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 配置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      # 安装依赖
      - name: Install dependencies
        run: yarn --frozen-lockfile

      # 打包并生成静态文件
      # - name: Build site
      #   run: yarn docs:build
      # 推送静态文件到分支
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # 部署到 gh-pages 分支
          target_branch: blogs
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
          cname: arashitake.github.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # # 使用别人写好的一个 action
        # uses: peaceiris/actions-gh-pages@v4
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   # 打包后的文件部署到哪个分支上
        #   publish_branch: blogs
        #   # 静态文件生成目录
        #   publish_dir: ./docs/.vuepress/dist
        #   cname: arashitake.github.io
